version: '3.5'

services:

  manago-db:
    container_name: manago-db
    image: mysql:5
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=manago_project
    - MYSQL_HOST=%
    volumes:
    - /data/mysql
    ports:
    - 3306:3306
    networks:
    - manago

  manago-myadmin:
    restart: always
    container_name: manago-myadmin
    image: phpmyadmin/phpmyadmin
    environment:
    - PMA_HOST=manago-db
    depends_on:
    - manago-db
    ports:
    - 8000:80
    networks:
    - manago

networks:
  manago:
    driver: bridge
