version: '3.5'

services:

  project-frontend:
    container_name: angular-fe
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - '../frontend:/usr/src/app'
      - '../frontend/usr/src/app/node_modules'
    ports:
      - '4200:4200'
    networks:
      - manago

  project-backend:
    container_name: node-be
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - '49160:8080'
    networks:
      - manago

  project-db:
    container_name: mysql-db
    image: mysql:5
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=manago
      - MYSQL_HOST=%
    volumes:
      - /data/mysql
    ports:
      - 3306:3306
    networks:
      - manago

  project-myadmin:
    restart: always
    container_name: phpmy-db
    image: phpmyadmin/phpmyadmin
    ports:
      - 8000:80
    environment:
      - PMA_HOST=mysql-db
    depends_on:
      - project-db
    ports:
      - 8080:80
    networks:
      - manago

networks:
  manago:
    driver: bridge
