CREATE TABLE IF NOT EXISTS CustomerProject (
    customerId INTEGER NOT NULL REFERENCES Customer (customerId) ON DELETE RESTRICT ON UPDATE CASCADE,
    projectName VARCHAR(100) REFERENCES Project (name) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=INNODB;
